<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class AutoDescsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tags = collect([
            'first_impact' => [
                'Oportunidade única em [neighborhood]. [property_type] com',
                'Sua vez de morar em [neighborhood]. [property_type] com',
                'Seu lar, doce lar em [neighborhood]. [property_type] com',
                'As melhores oportunidades estão em [neighborhood]. [property_type] com',
                'Venha morar no [neighborhood]! [property_type] com',
                'More no [neighborhood]! [property_type] com',
                '[neighborhood] está te esperando! [property_type] com',
                'Vem ser feliz no [neighborhood]! [property_type] com',
                'O desejo de morar em [neighborhood] vai se realizar! [property_type] com',
                'Venha viver em [neighborhood]! [property_type] com',
                'Sua casa em [neighborhood]! [property_type] com',
                'Viva em [neighborhood]! [property_type] com',
                'Seu lar em [neighborhood]! [property_type] com',
                'Faça de [neighborhood] seu lar! [property_type] com',
                'Faça de [neighborhood] seu final feliz! [property_type] com',
                'Venha ser feliz em [neighborhood]. [property_type] com',
                'Realize seus sonhos morando em [neighborhood]. [property_type] com',
                '[neighborhood] é seu novo destino! [property_type] com',
                'Seu endereço agora é em [neighborhood]! [property_type] com',
                'Aproveite o melhor da vida morando em [neighborhood]. [property_type] com',
                'Você e sua família morando em [neighborhood]. [property_type] com',
                'Seus sonhos te esperam em [neighborhood]! [property_type] com',
                'Seu sonho de morar em [neighborhood] é possível! [property_type] com',
                'Seu sonho de viver em [neighborhood] transformado em realidade! [property_type] com',
                'Você, feliz! Morando em [neighborhood]. [property_type] com',
                'Seu novo lar está em [neighborhood]. [property_type] com',
                'Aproveite as vantagens de morar em [neighborhood]. [property_type] com',
                'A moradia dos seus sonhos em [neighborhood]. [property_type] com',
                'Bem vindo a seu lar, doce lar em [neighborhood]! [property_type] com',
                'O melhor da vida está te esperando em [neighborhood]. [property_type] com',
                'Sua família morando em [neighborhood]. [property_type] com',
                '[neighborhood] ficará mais completo com você! [property_type] com',
                'Que tal morar em [neighborhood]? [property_type] com',
                'More onde sempre sonhou, more em [neighborhood]. [property_type] com',
                'Morando em [neighborhood], você nunca mais vai desejar outro lugar. [property_type] com',
                'Desfrute todas as vantagens em [neighborhood]. [property_type] com',
                'Não deixe a oportunidade passar! [property_type] em [neighborhood] com',
                'Viva o melhor que cidade pode oferecer em [neighborhood]. [property_type] com',
                'Contemple o que há de melhor em [neighborhood]. [property_type] com',
                'Aprecie toda comodidade de morar em [neighborhood]. [property_type] com',
                'É sua vez de ter dizer: lar, doce lar morando em [neighborhood]. [property_type] com',
                'Acredite! Você também pode morar em [neighborhood]. [property_type] com',
                'Desfrute o bem-estar de morar em [neighborhood]. [property_type] com',
                'Sinta-se em casa em [neighborhood]. [property_type] com',
                'Explore todas as qualidades de morar em [neighborhood]. [property_type] com',
                'Não perca essa oportunidade em [neighborhood]! [property_type] com',
                'Seu novo lar te espera em [neighborhood]! [property_type] com',
                'Sua chance de morar em [neighborhood]. [property_type] com',
                'Grande oportunidade para morar em [neighborhood]. [property_type] com',
                'Boa oportunidade para quem quer morar em [neighborhood]. [property_type] com',
                'Destaque em [neighborhood]! [property_type] com',
                'O imóvel que você busca em [neighborhood] está aqui! [property_type] com',
                'Não perca tempo! O imóvel que você busca está aqui. [property_type] com',
                'Sua busca pelo imóvel ideal terminou! [property_type] com',
                'Viva ao lado do que mais te inspira, viva em [neighborhood]. [property_type] com',
                '[neighborhood] tem tudo o que você procura. [property_type] com',
                'O lugar ideal para você e sua família é em [neighborhood]. [property_type] com',
                '[neighborhood] é onde seu sonho se torna realidade. [property_type] com',
                '[neighborhood], um lar para chamar de seu. [property_type] com',
                'Sua chance de morar em [neighborhood]. [property_type] com',
                'Não perca esta oportunidade de morar em [neighborhood]. [property_type] com',
                'Oportunidade única para morar em [neighborhood]. [property_type] com',
                'Venha morar em [neighborhood] e realize seu sonho! [property_type] com',
                '[neighborhood] está te esperando! [property_type] com',
                'Mais comodidade para você em [neighborhood]. [property_type] com',
                '[neighborhood] nunca esteve tão perto de você. [property_type] com',
                'O seu futuro está em [neighborhood]. [property_type] com',
                'Você já pensou de morar em [neighborhood]? [property_type] com',
                'Venha ser feliz em [neighborhood]. [property_type] com',
                'Sua felicidade nunca esteve tão perto, venha para [neighborhood]! [property_type] com',
                'Seu sonho está te esperando em [neighborhood]. [property_type] com',
                'Mude agora para [neighborhood]! [property_type] com',
                'Sua chance de realizar seu sonho em [neighborhood]! [property_type] com',
                'Em [neighborhood] as pessoas são mais felizes! [property_type] com',
                'Um novo olhar em [neighborhood]. [property_type] com',
                'Sua casa nova está em [neighborhood]. [property_type] com',
                'Conheça as vantagens de morar em [neighborhood]. [property_type] com',
                'Bem vindo ao seu novo lar no [neighborhood]. [property_type] com',
                'Seu novo lar fica em [neighborhood]. [property_type] com',
                'Encontre sua casa nova em [neighborhood]. [property_type] com',
                'Descubra o que há de melhor em [neighborhood]. [property_type] com',
                'Descubra o prazer de morar em [neighborhood]. [property_type] com',
                'Seu novo lar te espera no [neighborhood]. [property_type] com',
                'Faça de [neighborhood] seu mais novo lar! [property_type] com',
                'Encontre o melhor da vida em [neighborhood]. [property_type] com',
                'Visite oportunidade em [neighborhood]. [property_type] com',
                'Apareceu agora está oportunidade em [neighborhood]. [property_type] com',
                'Conquiste um estilo de vida tranquila morando em [neighborhood]. [property_type] com',
                'Sempre quis morar em [neighborhood]? Agora é sua chance de realizar esse sonho. [property_type] com',
                'Finalmente chegou no mercado! [property_type] que você precisa conhecer em [neighborhood] com',
                'Perto de tudo em [neighborhood]! [property_type] para morar bem com',
                'Seja bem-vindo em [neighborhood]! [property_type] com',
                'Em [neighborhood] você encontra essa chance única! [property_type] com',
                'No coração de [neighborhood] você encontra essa oportunidade! [property_type] com',
                'Venha morar com sofisticação em [neighborhood]. [property_type] com',
                'Impecável em [neighborhood]. [property_type] com',
                'Que tal morar em [neighborhood]? [property_type] com',
            ],

            'area' => [
              '[area]m²,',
            ],

            'bedroom_eq_0' => [
                'ambientes inteligentes e espaços interligados.',
                'espaço confortável e ambientes agrupados.',
                'espaço funcional e cômodos interligados.',
                'ambiente adaptável e cômodos agrupados.',
                'ambiente prático e cômodos compartilhados.',
                'espaço contemporâneo e cômodos interligados.',
                'espaço inovador e cômodos compartilhados.',
                'espaço arrojado e cômodos interligados.',
                'espaço privativo e ambientes interligados.',
                'espaço criativo e ambientes compartilhados.',
                'espaço engenhoso e ambientes agrupados.',
                'estrutura criativa e espaço interligados.',
                'estrutura prática e cômodos interligados.',
                'estrutura diferenciada e ambientes interligados.',
                'disposição prática e dependências interligadas.',
                'disposição moderna e dependências compartilhadas.',
                'disposição criativa e dependências agrupadas.',
                'disposição confortável e ambientes interligados.',
                'ambiente criativo e dependências compartilhadas.',
                'ambiente contemporâneo e espaços interligados.',
                'ambiente agradável e espaços interligados.',
                'espaços agradáveis e ambientes compartilhados.',
                'estrutura agradável e cômodos agrupados.',
                'dependências confortáveis e cômodos agrupados.',
                'espaços confortáveis e ambientes interligados.',
                'disposição confortável e ambientes agrupados.',
                'proporções aconchegantes e ambientes interligados.',
                'proporções aconchegantes e dependências agrupadas.',
                'clima agradável e dependências compartilhadas.',
                'arranjo confortável e dependências interligadas.',
                'disposição diferenciada e prática.',
                'ambiente arrojado e cômodos funcionais.',
                'espaço, bom aproveitamento e distribuição despojada.',
                'espaço acolhedor e cômodos agrupados.',
                'ambiente acolhedor e espaços interligados.',
                'espaço acolhedor e ambientes inteligentes.',
                'ambientes funcionais que proporcionam praticidade.',
                'conforto em espaço compacto.',
                'ambiente compacto e clean.',
                'design arrojado e ótimo espaço interno.',
                'conforto e praticidade em espaços interligados.',
                'ambiente criativo e espaço funcional.',
                'espaço aconchegante e ambientes interligados.',
                'dependências aconchegantes e cômodos compartilhados.',
                'boa utilização do espaço e ambientes interligados.',
                'boa utilização do espaço e dependências agrupadas.',
                'ambiente moderno e cômodos interligados.',
                'ambiente moderno e dependências compartilhadas.',
                'ambiente criativo e espaço funcional.',
            ],

            'bedroom_eq_1' => [
                'design adaptável e 1 dormitório.',
                'cômodos funcionais e 1 dormitório.',
                'arquitetura diferenciada e 1 dormitório.',
                'espaço dinâmico e 1 dormitório.',
                'ambiente privativo e 1 dormitório.',
                'ambiente arrojado e 1 dormitório.',
                'ambiente engenhoso e 1 dormitório.',
                'espaço reservado e 1 dormitório.',
                'design funcional e 1 dormitório.',
                'ambiente funcional e 1 dormitório.',
                'espaço moderno e 1 dormitório.',
                'estrutura completa e 1 dormitório.',
                'infraestrutura individual e 1 dormitório.',
                'ambiente confortável e 1 dormitório.',
                'praticidade, conforto e 1 dormitório.',
                'estrutura adaptável e 1 dormitório.',
                'estrutura funcional e 1 dormitório.',
                'design prático e 1 dormitório.',
                'proporções inteligentes e 1 dormitório.',
                'proporções ideais para você e 1 dormitório.',
                'proporções aconchegantes e harmoniosas e 1 dormitório.',
                'ambientes convidativos e 1 dormitório.',
                'ambientes aconchegantes e 1 dormitório.',
                'ambientes funcionais e 1 dormitório.',
                'estrutura adaptável  e 1 dormitório.',
                'ambientes adaptáveis e 1 dormitório.',
                'ambiente versátil e 1 dormitório.',
                'espaço convidativo e 1 dormitório.',
                'versatilidade, ambientes funcionais e 1 dormitório.',
                'ambientes completos e 1 dormitório.',
                'ambiente arrojado e 1 dormitório.',
                'espaços bem aproveitados e 1 dormitório.',
                'disposição diferenciada e 1 dormitório.',
                'design moderno e 1 dormitório.',
                'ambiente diferenciado e 1 dormitório.',
                'design inteligente e 1 dormitório.',
                'ambiente do tamanho ideal e 1 dormitório.',
                'ambiente acolhedor e 1 dormitório.',
                'ambientes aconchegantes e 1 dormitório.',
                'design criativo e 1 dormitório.',
                'design moderno e 1 dormitório.',
                'conforto, praticidade e 1 dormitório.',
                'ambiente agradável e 1 dormitório.',
                'espaço agradável e 1 dormitório.',
                'espaço aconchegante e 1 dormitório.',
                'espaços criativos, aconchegantes e 1 dormitório.',
                'a medida certa para você e 1 dormitório.',
                'espaço ideal para solteiros ou casais, completo e 1 dormitório.',
                'espaço bem planejado e 1 dormitório.',
            ],

            'bedroom_eq_2' => [
                'conforto, praticidade e 2 domitórios.',
                'design ideal para você e possui 2 domitórios.',
                'conforto, acolhimento e ainda possui 2 domitórios.',
                'estrutura inovadora, confortável e possui 2 domitórios.',
                'espaços aconchegante, ambientes funcionais e possui 2 domitórios.',
                'ambientes convidativos, confortáveis e possui 2 domitórios.',
                'ambiente acolhedor, dinâmico e possui 2 domitórios.',
                'espaço acolhedor, ideal para você e possui 2 domitórios.',
                'condições perfeitas para você e 2 domitórios.',
                'ambientes agradáveis, funcionais e possui 2 domitórios.',
                'estrutura funcional, agradável e possui 2 dormitórios.',
                'estrutura completa, espaço acolhedor e possui 2 dormitórios.',
                'espaços agradáveis, muita praticidade e possui 2 dormitórios.',
                'estrutura moderna e 2 dormitórios.',
                'espaços aconchegantes, em excelentes condições e possui 2 dormitórios.',
                'ambientes funcionais, acolhedores e possui 2 dormitórios.',
                'cômodos modernos e possui 2 dormitórios.',
                'design moderno e possui 2 dormitórios.',
                'design adaptável e possui 2 dormitórios.',
                'ambiente funcional e possui 2 dormitórios.',
                'área agradável, clima convidativo e possui 2 dormitórios.',
                'conforto, estrutura adaptável e possui 2 dormitórios.',
                'estrutura adaptável, possui estrutura completa e 2 dormitórios.',
                'design agradável, possui ambientes convidativos e 2 dormitórios.',
                'design confortável, prático e possui 2 dormitórios.',
                'área confortável, aconchegante e 2 dormitórios.',
                'ambientes aconchegantes e 2 dormitórios.',
                'área aconchegante, possui design convidativo e 2 dormitórios.',
                'área agradável, possui design completo e 2 dormitórios.',
                'espaços convidativos e possui 2 dormitórios.',
                'ambientes planejados, perfeito para a famílias crescendo e 2 dormitórios.',
            ],

            'bedroom_eq_3' => [
                'estrutura ideal e 3 dormitórios.',
                'arquitetura moderna e 3 dormitórios.',
                'dimensões modernas e 3 dormitórios.',
                'ambientes inteligentes e 3 dormitórios.',
                'disposição perfeita de ambientes e 3 dormitórios.',
                'conforto, funcionalidade e 3 dormitórios.',
                'disposição funcional e 3 dormitórios.',
                'estrutura impecável e 3 dormitórios.',
                'estrutura moderna, acolhedora e 3 dormitórios.',
                'design inteligente e 3 dormitórios.',
                'plena comodidade e 3 dormitórios.',
                'inovação, modernidade e 3 dormitórios.',
                'estrutura contemporânea e 3 dormitórios.',
                'estrutura perfeita e 3 dormitórios.',
                'estrutura completa e 3 dormitórios.',
                'estrutura dinâmica e 3 dormitórios.',
                'estrutura inteligente e 3 dormitórios.',
                'estrutura funcional e 3 dormitórios.',
                'design funcional e 3 dormitórios.',
                'design completo e 3 dormitórios.',
                'design inteligente e 3 dormitórios.',
                'estrutura convidativa, completa e 3 dormitórios.',
                'estrutura completa, pleno conforto e 3 dormitórios.',
                'pleno conforto, estrutura acolhedora e 3 dormitórios.',
                'espaço inteligente, estrutura convidativa e 3 dormitórios.',
                'ambientes convidativos, pleno conforto e 3 dormitórios.',
                'pleno conforto, ambiente agradável e 3 dormitórios.',
                'espaço dinâmico, adaptável e 3 dormitórios.',
                'design inteligente, aconchegante e 3 dormitórios.',
                'espaço funcional, confortável e 3 dormitórios.',
                'espaços bem planejados, funcionais e 3 dormitórios, acomodação até para a sogra!',
                'ambiente moderno, amplo e ainda 3 dormitórios.',
            ],

            'bedroom_gte_4' => [
                'estrutura completa e [bedrooms] dormitórios.',
                'estrutura ilimitada e [bedrooms] dormitórios.',
                'estrutura perfeita e [bedrooms] dormitórios.',
                'estrutura confortável e [bedrooms] dormitórios.',
                'arquitetura acolhedora e [bedrooms] dormitórios.',
                'arquitetura diferenciada e [bedrooms] dormitórios.',
                'arquitetura personalizada e [bedrooms] dormitórios.',
                'arquitetura singular e [bedrooms] dormitórios.',
                'arquitetura funcional e [bedrooms] dormitórios.',
                'arquitetura adaptável e [bedrooms] dormitórios.',
                'arquitetura inteligente e [bedrooms] dormitórios.',
                'arquitetura dinâmica e [bedrooms] dormitórios.',
                'arquitetura moderna e [bedrooms] dormitórios.',
                'arquitetura inovadora e [bedrooms] dormitórios.',
                'arquitetura contemporânea e [bedrooms] dormitórios.',
                'design contemporâneo e [bedrooms] dormitórios.',
                'design inovador e [bedrooms] dormitórios.',
                'design singular e [bedrooms] dormitórios.',
                'design dinâmico e [bedrooms] dormitórios.',
                'design diferenciado e [bedrooms] dormitórios.',
                'ambientes estruturados, adaptáveis e [bedrooms] dormitórios.',
                'design, estrutura convidativa e [bedrooms] dormitórios.',
                'ambientes completos, arquitetura aconchegante e [bedrooms] dormitórios.',
                'arquitetura agradável, ambientes acolhedores e [bedrooms] dormitórios.',
                'design acolhedor, estrutura prática, completa e [bedrooms] dormitórios.',
                'design diferenciado, convidativo e [bedrooms] dormitórios.',
                'design inteligente, estrutura convidativa e [bedrooms] dormitórios.',
                'estrutura completa, acolhedora e [bedrooms] dormitórios.',
                'ambientes inteligentes, estrutura convidativa e [bedrooms] dormitórios.',
                'arquitetura diferenciada, inteligente e [bedrooms] dormitórios.',
                'espaço, conforto e [bedrooms] dormitórios.',
                'dependências completas e [bedrooms] dormitórios.',
                'espaço, conforto e [bedrooms] dormitórios.',
                'ambientes completos, para toda a família e [bedrooms] dormitórios.',
                'design criativo, ambientes amplos, confortáveis e [bedrooms] dormitórios.',
                'design criativo, ambientes aconchegantes e [bedrooms] dormitórios.',
                'estrutura moderna e [bedrooms] dormitórios.',
                'estrutura inovadora, ambientes convidativos e [bedrooms] dormitórios.',
                'inovação, conforto e [bedrooms] dormitórios.',
                'design único, ambientes inteligentes e [bedrooms] dormitórios.',
            ],

            'price_20_lt_avg' => [
                'Um achado!',
                'O melhor preço do mercado!',
                'Melhor momento para fechar negócio!',
                'Melhor oportunidade do mercado!',
                'Um verdadeiro presente!',
                'As melhores condições do mercado!',
                'Não deixe para depois!',
                'Oportunidade imperdível!',
                'Sua melhor chance!',
                'Sua melhor oportunidade de negócio!',
                'Um verdadeiro achado!',
                'O melhor que você vai encontrar!',
                'O mercado está a seu favor!',
                'Com as melhores condições!',
                'Sua melhor oportunidade hoje!',
                'A melhor oportunidade de investimento!',
                'Essa é a sua chance de fechar o melhor negócio!',
                'O melhor preço da região!',
                'Um achado com as melhores condições!',
                'O mercado está te favorecendo, aproveite!',
                'Alerta de melhor oportunidade!',
                'Garantia de melhor negócio!',
                'Aproveite o melhor momento para investir!',
                'O melhor momento para o seu investimento!',
                'Um achado no mercado!',
                'Custo benefício incrível!',
                'Melhor momento para investir!',
                'Sua chance de realizar o melhor negócio!',
                'Aproveite o mercado a seu favor!',
                'Melhor hora para fechar negócio!',
                'Não perca esta oportunidade!',
                'Você não pode ficar fora dessa!',
                'Não deixe essa chance passar, aproveite!',
                'Garanta já, é sua chance de aproveitar os melhores valores!',
                'Uma excelente oportunidade!',
                'O melhor custo benefício!',
                'Garanta o melhor preço!',
                'Faça o seu melhor negócio!',
                'Não deixe essa oferta passar, preço imperdível!',
                'Condições incríveis!',
                'Não perca essa oportunidade!',
                'Oportunidade única para fechar um excelente negócio!',
                'Faça um negócio incrível!',
                'Melhor opção para investimento!',
                'Não deixe essa oportunidade de ouro escapar!',
                'Não deixe para amanhã, faça o melhor negócio agora mesmo!',
                'Preço muito abaixo da média. Não perca essa chance!',
                'O melhor preço para um ótimo negócio!',
                'Faça um excelente negócio, pagando muito abaixo da média!',
                'Valor excelente no mercado!',
                'Super desconto com base no valor de mercado!',
                'Uma pechincha, não perca essa oportunidade!',
                'Imóvel com preço muito abaixo do mercado, confira!',
                'A hora de negociar é agora, o melhor preço do mercado!',
                'O melhor preço por m², não perca essa oportunidade!',
            ],

            'price_bt_2_n_19_lt_avg' => [
                'Excelente oportunidade de negócio!',
                'Aproveite a chance!',
                'Excelente negócio!',
                'Momento excelente para fechar!',
                'Essa oportunidade vale a pena!',
                'Ótimo momento para fazer negócio!',
                'Aproveite, vale a pena!',
                'Oportunidade de ouro!',
                'Realize um excelente negócio!',
                'Não perca essa oportunidade de ouro!',
                'Não perca essa excelente oportunidade!',
                'Chance de negócio excelente!',
                'Não deixe essa oportunidade passar!',
                'Aproveite agora essa excelente oportunidade!',
                'Investimento excelente!',
                'Realize um investimento excelente!',
                'Ótimo momento para investir!',
                'Ótimo momento para fechar!',
                'Sua chance de realizar um ótimo investimento!',
                'Sua chance de negociar com excelentes condições!',
                'Excelente opção de negócio!',
                'Ótima escolha de investimento!',
                'Um negócio excelente!',
                'Está diante de um ótimo negócio!',
                'Ótimo dia para fechar negócio!',
                'Parabéns por encontrar uma oportunidade de ouro!',
                'Hora certa para aproveitar essa oportunidade excelente!',
                'Agarre essa excelente oportunidade!',
                'Alerta de oportunidade!',
                'Agarre essa oportunidade!',
                'Com ótimo preço, essa é sua oportunidade!',
                'Melhor preço praticado!',
                'Ótima oportunidade da região!',
                'Imóvel com ótimo preço, veja e compare!',
                'Boa chance para negociar sua casa nova.',
                'Preço do m² menor que a média, grande chance!',
                'Está procurando ótimos investimentos? Preço mais atrativo do mercado!',
            ],

            'price_eq_avg' => [
                'Bom investimento!',
                'Esse é um bom negócio!',
                'Faça um investimento seguro!',
                'Boas condições para negociação.',
                'Bom momento para investir.',
                'Investimento seguro!',
                'Aproveite essa oportunidade!',
                'Um bom negócio e com boas condições.',
                'Aproveite as boas condições do mercado.',
                'Boa oportunidade de investimento.',
                'Uma boa oportunidade no mercado.',
                'Mercado favorável e boas condições.',
                'Aproveite as boas condições!',
                'Mercado favorável para o investimento.',
                'Boas condições no mercado.',
                'Não perca a chance de realizar um bom negócio.',
                'Sua chance de fechar um bom negócio!',
                'Boa hora para negociar.',
                'Momento para um investimento seguro.',
                'Realize um bom negócio!',
                'Aproveite as condições favoráveis para fechar negócio!',
                'Aproveite o momento e boas condições para investir.',
                'Bom momento e boas condições.',
                'Boa hora para agarrar a oportunidade.',
                'Uma boa chance de realizar um negócio seguro.',
                'Oportunidade segura de investimento acertado.',
                'Aproveite as condições favoráveis do mercado.',
                'Boa chance de fechar negócio com boas condições.',
                'Boa oportunidade e momento para fechar negócio.',
                'Bom dia para investir.',
                'Ótimo preço!',
                'Oportunidade muito boa de negócio.',
                'Aproveite as ótimas condições do mercado!',
                'Sua grande chance para fechar um negócio seguro!',
                'Não perca essa oportunidade e feche um negócio seguro!',
                'Aproveite os bons valores do mercado!',
                'Bom momento para investir!',
                'Conheça mais sobre essa oportunidade!',
                'A sua estabilidade está aqui!',
                'Preço justo, saiba mais!',
            ],

            'price_gt_avg' => [
                'Mercado aquecido!',
                'Oportunidade de valorização.',
                'Seu investimento em um destaque no mercado!',
                'Essa é uma oportunidade em valorização!',
                'Em alta no mercado!',
                'Oportunidade de investimento em valorização!',
                'Oportunidade valorizada no mercado!',
                'Oportunidade de investimento aquecido no mercado.',
                'Chance de investimento com potencial de crescimento e valorização!',
                'Aproveite a chance em crescimento e valorização!',
                'Ótimo período e expectativas no setor imobiliário!',
                'Agarre a chance de fechar um negócio de destaque.',
                'Oportunidade em alta no mercado!',
                'Período de crescimento e com potencial de valorização.',
                'Negócio de destaque no mercado imobiliário!',
                'Investimento com potencial de valorização!',
                'Potencial de valorização e crescimento!',
                'Negócio com potencial de valorização!',
                'Faça um negócio com potencial real no setor imobiliário!',
                'Investimento em negócio com potencial!',
                'Oportunidade em valorização.',
                'Investimento em local valorizado e com boas expectativas no mercado.',
                'Seu momento de investir com potencial de crescimento.',
                'Alerta de período de crescimento e valorização!',
                'Um destaque no mercado com potencial de valorização!',
                'Invista em um destaque no mercado!',
                'Invista em um destaque em moradia!',
                'Oportunidade de investir em destaque para moradia!',
                'Destaque em moradia.',
                'Encontrou uma oportunidade em valorização!',
                'Sua hora de investir com oportunidades de crescimento!',
                'Preço valorizado e uma ótima chance para investimento.',
                'Ótima opção de investimento em período de valorização!',
            ],

            'real_state' => [
                'Entre em contato agora com [client].',
                'Fale agora com [client].',
                'Contate agora [client].',
                'Contate agora [client] e fale com o corretor.',
                'Entre em contato com [client], estão te esperando!',
                'Oferta de [client], entre em contato!',
                'Contate [client] para falar com o corretor.',
                'Contate agora [client] e converse com os corretores.',
                'Entre em contato com [client] e converse com um dos corretores.',
                'Entre em contato com [client] para falar com o corretor.',
                'Contate [client] para falar com um dos corretores.',
                'Entre em contato ainda hoje com [client].',
                'Fale com [client] e converse com o corretor.',
                'Fale com [client] o corretor está te esperando!',
                'Converse com [client], há um corretor te aguardando.',
                'Oferta de [client], converse com um dos corretores!',
                'Contate hoje [client] e fale com o corretor.',
                'Oferta exclusiva de [client], contate para falar com o corretor.',
                'Entre em contato com [client], há um corretor te aguardando!',
                'Contate [client] e converse com o corretor.',
                'Contate [client] e converse com o corretor.',
                'Contate hoje [client] e converse com um dos corretores.',
                'Fale com o corretor, contate agora [client].',
                'Fale com o corretor! Entre em contato com [client].',
                'O corretor está te aguardando! Contate [client].',
                'Converse com o corretor, contate hoje [client].',
                'Oferta exclusiva de [client], entre em contato sobre imóveis em [city].',
                'Oferta de [client], entre em e fale sobre imóveis em [city]!',
                'Fale agora com [client] sobre imóveis em [city].',
                'Contate [client] e fale com o corretor sobre imóveis em [city].',
            ],
        ]);

        $data = [];

        foreach($tags as $tag => $texts){
            $descs = array_map(function($text) use($tag){
                return [
                    'text' => $text,
                    'tag' => $tag,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()
                ];
            }, $texts);

            $data = array_merge($data, $descs);
        }

        DB::table('auto_descs')->insert($data);
    }
}
