version: '3'
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        xdebug_remote_addr: ${XDEBUG_REMOTE_ADDR}
    container_name: admin.videobrasil.online
    restart: always
    volumes:
      - .:/var/www/admin/
    ports:
      - "8080:80"
      - "8443:443"
      - "8000:8000"
    extra_hosts:
     - database-host:10.13.155.22
    networks:
      - server
  mysql57:
    image: mysql:5.7
    container_name: mysql57
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: q1w2e3r4
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8888:8080
networks:
  server:
    driver: overlay
